import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { pathToFileURL } from 'node:url';
import { mkdir, writeFile, readFile } from 'node:fs/promises';
import { createServer as createHttpServer } from 'node:http';
import path from 'node:path';
const project = path.resolve();
const require = createRequire(path.join(project, 'package.json'));
const { build } = await import(pathToFileURL(require.resolve('vite')).href);
const { default: react } = await import(pathToFileURL(require.resolve('@vitejs/plugin-react')).href);
const { chromium } = require('playwright');
const output = path.join(project, 'output/playwright/effect-data-inspector');
await mkdir(output, { recursive: true });
const harness = `
import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { EffectDataBindingInspector } from '/src/editor/panels/EffectDataBindingInspector';
import { createDefaultEffectConfiguration } from '/src/editor/model/effectConfigurationValidation';
import { useEditorStore } from '/src/editor/store/editorStore';
import { configureEffectDataTransport } from '/src/runtime/effects/EffectDataRuntime';
import '/src/styles/global.css';
const scene = {entityIds:[],entities:{},sceneSettings:{environment:null},selectedEntityId:null,mqttConfig:{subscriptions:[{topic:'fixture',adapter:{kind:'epv',sourceId:'factory-a'}}]}};
useEditorStore.setState({scene});
const state = {requests:[],commits:[],delay:15,aborts:0};
configureEffectDataTransport({transport:(request,signal)=>new Promise((resolve,reject)=>{
  state.requests.push(request);
  const timer=setTimeout(()=>resolve({success:true,data:{statusCode:200,responseBody:JSON.stringify({value:0,speed:2,password:'fixture-private',rows:[{id:'A',x:1,y:0,z:2,value:3,name:'区域A'}]})}}),state.delay);
  signal.addEventListener('abort',()=>{state.aborts++;clearTimeout(timer);reject(new Error('fixture cancelled'));},{once:true});
})});
function App(){
  const component = {effectKind:'data-bars',enabled:true,primaryColor:'#22ffff',secondaryColor:'#ffffff',intensity:1,speed:1,density:1};
  const [configuration,setConfiguration]=useState(()=>createDefaultEffectConfiguration(component));
  const [disabled,setDisabled]=useState(false);
  window.effectDataUi = {state,configuration,setDisabled,remount:()=>setConfiguration(createDefaultEffectConfiguration(component))};
  return <div style={{width:420,padding:18,margin:12,background:'#17232f',color:'#e7eff8'}}><h2>特效数据配置验证</h2><EffectDataBindingInspector component={component} configuration={configuration} disabled={disabled} onChange={(next,label)=>{state.commits.push({next,label});setConfiguration(next);}}/></div>;
}
createRoot(document.getElementById('root')).render(<App/>);
`;
await writeFile(path.join(output, 'harness.tsx'), harness, 'utf8');
const storeFixture = { name:'effect-data-store-fixture', enforce:'pre', resolveId(source, importer){ if(source==='/src/editor/store/editorStore' || source==='../store/editorStore' && importer?.endsWith('EffectDataBindingInspector.tsx')) return '\0effect-data-store'; }, load(id){ if(id==='\0effect-data-store') return "import {create} from 'zustand';export const useEditorStore=create(()=>({scene:null}));"; } };
console.log('building isolated UI fixture');
const bundle = path.join(output,'bundle');
await build({ configFile:false, root:project, plugins:[storeFixture,react()], define:{'process.env.NODE_ENV':'"production"'}, build:{lib:{entry:path.join(output,'harness.tsx'),formats:['es'],fileName:'fixture',cssFileName:'fixture'},outDir:bundle,emptyOutDir:false,minify:false} });
const server = createHttpServer(async (request,response)=>{
  const file=request.url==='/fixture.js'?'fixture.js':request.url==='/fixture.css'?'fixture.css':null;
  response.setHeader('Content-Type',file?.endsWith('.js')?'application/javascript':file?.endsWith('.css')?'text/css':'text/html');
  response.end(file?await readFile(path.join(bundle,file)):'<!doctype html><html><head><meta charset="utf-8"><link rel="stylesheet" href="/fixture.css"></head><body><div id="root"></div><script type="module" src="/fixture.js"></script></body></html>');
});
let browser;
const errors = [];
try {
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  browser = await chromium.launch({ channel: 'msedge', headless: true });
  const page = await browser.newPage({ viewport: { width: 1000, height: 1050 } });
  page.on('pageerror', error => { errors.push(error.message); console.error(error.message); });
  page.setDefaultTimeout(60000);
  await page.goto('http://127.0.0.1:'+server.address().port+'/', { waitUntil: 'commit' });
  console.log('opened data UI fixture');
  await page.getByRole('group', { name: '数据绑定', exact: true }).waitFor();
  console.log('data UI rendered');
  await page.getByLabel('特效数据来源').selectOption('http');
  await page.getByLabel('托管数据源 ID', { exact: true }).fill('42');
  await page.getByLabel('资产编号', { exact: true }).fill('000317');
  assert.deepEqual(await page.evaluate(() => [window.effectDataUi.state.requests.length,window.effectDataUi.state.commits.length]), [0,0]);
  await page.getByRole('button', { name: '测试取数', exact: true }).click();
  await page.getByRole('status').filter({hasText:'状态：在线'}).waitFor();
  console.log('HTTP explicit test completed');
  assert.equal(await page.evaluate(() => window.effectDataUi.state.requests.length), 1);
  assert.equal(await page.evaluate(() => window.effectDataUi.state.requests[0].assetCode), '000317');
  assert.equal(await page.getByLabel('特效数据字段样例').innerText().then(text => text.includes('fixture-private')), false);
  await page.getByRole('button', { name: '添加字段映射', exact: true }).click();
  await page.getByLabel('映射 1 数据字段', { exact: true }).fill('speed');
  await page.getByLabel('映射 1 目标属性', { exact: true }).selectOption('speed');
  await page.getByLabel('映射 1 倍率', { exact: true }).fill('0.1');
  await page.getByRole('button', { name: '应用数据配置', exact: true }).click();
  await page.waitForFunction(() => window.effectDataUi.state.commits.length === 1);
  assert.equal(await page.evaluate(() => window.effectDataUi.configuration.data.assetCode), '000317');
  assert.equal(await page.evaluate(() => window.effectDataUi.configuration.data.mappings[0].scale), 0.1);
  await page.getByLabel('启用空间数据集').check();
  await page.getByLabel('记录数组路径', { exact: true }).fill('rows');
  await page.getByLabel('坐标换算倍率', { exact: true }).fill('0.001');
  await page.getByLabel('数据集坐标空间', { exact: true }).selectOption('world');
  await page.getByText('条件触发', { exact: true }).click();
  await page.getByLabel('启用条件触发').check();
  await page.getByLabel('触发字段', { exact: true }).fill('speed');
  await page.getByLabel('触发比较关系').selectOption('gt');
  await page.getByLabel('比较值', { exact: true }).fill('0');
  await page.getByLabel('触发去抖 (ms)', { exact: true }).fill('50');
  await page.getByRole('button', { name: '应用数据配置', exact: true }).click();
  await page.waitForFunction(() => window.effectDataUi.state.commits.length === 2);
  assert.equal(await page.evaluate(() => window.effectDataUi.configuration.data.dataset.enabled), true);
  assert.equal(await page.evaluate(() => window.effectDataUi.configuration.data.dataset.unitScale), .001);
  assert.equal(await page.evaluate(() => window.effectDataUi.configuration.data.dataset.coordinateSpace), 'world');
  assert.equal(await page.evaluate(() => window.effectDataUi.configuration.data.trigger.enabled), true);
  await page.getByText('枚举映射（0 项）', { exact: true }).click();
  await page.getByLabel('映射 1 枚举 JSON').fill('[{"value":"2","output":false}]');
  await page.waitForFunction(() => [...document.querySelectorAll('button')].find(button => button.textContent === '应用数据配置')?.disabled === true);
  assert.equal(await page.evaluate(() => window.effectDataUi.state.commits.length), 2);
  assert.equal(await page.getByRole('button', { name: '应用数据配置', exact: true }).isDisabled(), true);
  await page.getByRole('button', { name: '应用枚举草稿', exact: true }).click();
  await page.getByLabel('映射 1 目标属性', { exact: true }).selectOption('enabled');
  await page.getByRole('button', { name: '应用数据配置', exact: true }).click();
  await page.waitForFunction(() => window.effectDataUi.state.commits.length === 3);
  await page.getByLabel('映射 1 数据字段').fill('__proto__.bad');
  await page.getByRole('button', { name: '应用数据配置', exact: true }).click();
  await page.getByRole('alert').filter({hasText:'字段路径或目标属性无效'}).waitFor();
  assert.equal(await page.evaluate(() => window.effectDataUi.state.commits.length), 3);
  await page.getByRole('button', { name: '放弃修改', exact: true }).click();
  await page.evaluate(() => {window.effectDataUi.state.delay = 5000;});
  await page.getByRole('button', { name: '测试取数', exact: true }).click();
  await page.getByRole('button', { name: '停止测试', exact: true }).waitFor();
  await page.getByRole('button', { name: '停止测试', exact: true }).click();
  await page.waitForFunction(() => window.effectDataUi.state.aborts === 1);
  await page.evaluate(() => {window.effectDataUi.setDisabled(true);});
  await page.waitForFunction(() => [...document.querySelectorAll('.effect-data-inspector input,.effect-data-inspector select,.effect-data-inspector textarea,.effect-data-inspector button')].every(element => element.disabled));
  await page.evaluate(() => {window.effectDataUi.setDisabled(false);window.effectDataUi.state.delay = 15;});
  await page.getByRole('button', { name: '测试取数', exact: true }).click();
  await page.getByRole('status').filter({hasText:'状态：在线'}).waitFor();
  await page.screenshot({ path: path.join(output, 'data-inspector.png'), fullPage: true });
  await page.getByLabel('特效数据来源').selectOption('mqtt');
  await page.getByLabel('MQTT 数据源', { exact: true }).fill('factory-a');
  await page.getByLabel('协议设备类型', { exact: true }).fill('rgv');
  assert.equal(await page.locator('datalist option[value="factory-a"]').count(), 1);
  await page.getByRole('button', { name: '应用数据配置', exact: true }).click();
  await page.waitForFunction(() => window.effectDataUi.state.commits.length === 4);
  assert.equal(await page.evaluate(() => window.effectDataUi.configuration.data.sourceId), 'factory-a');
  await page.getByLabel('特效数据来源').selectOption('inherit');
  await page.getByRole('button', { name: '测试取数', exact: true }).click();
  await page.getByRole('alert').filter({hasText:'目标尚无完整设备数据身份'}).waitFor();

  // 删除草稿行后，相同枚举初值的后继行必须保留自己的草稿身份。
  await page.evaluate(() => window.effectDataUi.remount());
  await page.waitForFunction(() => document.querySelector('[aria-label="特效数据来源"]')?.value === 'none');
  await page.getByLabel('特效数据来源').selectOption('http');
  await page.getByLabel('托管数据源 ID', {exact:true}).fill('42');
  await page.getByLabel('资产编号', {exact:true}).fill('000317');
  for(let index=1;index<=2;index++){
    await page.getByRole('button',{name:'添加字段映射',exact:true}).click();
    await page.getByLabel('映射 '+index+' 数据字段',{exact:true}).fill('speed');
    await page.getByLabel('映射 '+index+' 目标属性',{exact:true}).selectOption('speed');
  }
  await page.getByText('枚举映射（0 项）',{exact:true}).nth(0).click();
  await page.getByLabel('映射 1 枚举 JSON').fill('[{"value":"2","output":false}]');
  await page.waitForFunction(() => [...document.querySelectorAll('button')].find(button => button.textContent === '应用数据配置')?.disabled === true);
  assert.equal(await page.getByRole('button',{name:'应用数据配置',exact:true}).isDisabled(),true);
  await page.getByRole('button',{name:'删除映射 1',exact:true}).click();
  await page.getByText('枚举映射（0 项）',{exact:true}).click();
  assert.equal(await page.getByLabel('映射 1 枚举 JSON').inputValue(),'[]');
  assert.equal(await page.getByRole('button',{name:'应用数据配置',exact:true}).isEnabled(),true);
  await page.getByRole('button',{name:'应用数据配置',exact:true}).click();
  await page.waitForFunction(()=>window.effectDataUi.state.commits.length===5);
  assert.deepEqual(await page.evaluate(()=>window.effectDataUi.configuration.data.mappings[0].values),[]);
  await page.getByLabel('启用空间数据集').check();
  await page.getByLabel('Y 坐标字段',{exact:true}).fill('');
  await page.getByRole('button',{name:'应用数据配置',exact:true}).click();
  await page.getByRole('alert').filter({hasText:'数据集 yPath 字段路径无效'}).waitFor();
  assert.equal(await page.evaluate(()=>window.effectDataUi.state.commits.length),5);
  assert.deepEqual(errors, []);
  console.log(JSON.stringify({passed:true,requests:await page.evaluate(()=>window.effectDataUi.state.requests.length),commits:await page.evaluate(()=>window.effectDataUi.state.commits.length),aborts:await page.evaluate(()=>window.effectDataUi.state.aborts),errors,screenshot:path.join(output,'data-inspector.png')},null,2));
} finally { await browser?.close(); server.closeAllConnections(); await new Promise(resolve=>server.close(resolve)); }
