import assert from 'node:assert/strict';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { createServer } from 'node:http';
import { createRequire } from 'node:module';
import path from 'node:path';
import { pathToFileURL } from 'node:url';

const project = path.resolve();
const require = createRequire(path.join(project, 'package.json'));
const { build } = await import(pathToFileURL(require.resolve('vite')).href);
const { default: react } = await import(pathToFileURL(require.resolve('@vitejs/plugin-react')).href);
const { chromium } = require('playwright');
const output = path.join(project, 'output/playwright/multi-effect-binding');
await mkdir(output, { recursive: true });
const harness = `
import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import {EffectConfigurationInspector} from '/src/editor/panels/EffectConfigurationInspector';
import {createDefaultEffectConfiguration} from '/src/editor/model/effectConfigurationValidation';
import {useEditorStore} from '/src/editor/store/editorStore';
import {deviceTelemetryStore} from '/src/runtime/mqtt/deviceTelemetry';
import {publishEffectDiagnostic} from '/src/runtime/effects/effectDiagnostics';
import '/src/styles/global.css';
const model=(id,name,code)=>({id,name,components:{modelAsset:{sourcePath:'C:/fixture/device.glb',sourceUrl:'editor-asset://local/device.glb',assetCode:code},telemetryBinding:{sourceId:'factory-a',deviceType:'rgv',assetCode:code}}});
const scene={entityIds:['m1','m2','m3','generator','effect'],entities:{m1:model('m1','设备一','0001'),m2:model('m2','设备二','0002'),m3:model('m3','设备三','0003'),generator:{id:'generator',name:'设备生成器',components:{modelGenerator:{}}},effect:{id:'effect',name:'测试特效',components:{poiEffect:{}}}},sceneSettings:{environment:null},selectedEntityId:'effect',mqttConfig:{subscriptions:[{topic:'fixture',adapter:{kind:'epv',sourceId:'factory-a'}}]}};
useEditorStore.setState({scene,hierarchySelectionIds:['effect','m1','m2']});
const initial={effectKind:'building-outline',enabled:true,primaryColor:'#22ffff',secondaryColor:'#ffffff',intensity:1,speed:1,density:1,visual:{targetEntityId:'m1'}};
initial.configuration=createDefaultEffectConfiguration(initial);
const state={commits:0};
function App(){const [component,setComponent]=useState(initial);const [disabled,setDisabled]=useState(false);
window.multiUi={state,component,setDisabled,setComponent,diagnostic:value=>publishEffectDiagnostic('effect',value),setSelection:ids=>useEditorStore.setState({hierarchySelectionIds:ids}),removeModel:id=>{const current=useEditorStore.getState().scene;const entities={...current.entities};delete entities[id];useEditorStore.setState({scene:{...current,entities,entityIds:current.entityIds.filter(value=>value!==id)}});},publish:code=>deviceTelemetryStore.upsert({sourceId:'factory-a',assetCode:code,deviceType:'rgv',topic:'fixture',payloadDeviceCode:null,sourceTimestamp:Date.now(),sequence:1,receivedAt:Date.now(),fields:{speed:2},currentLocationKey:null,targetLocationKey:null,hasTargetLocation:false,faulted:false,message:''})};
return <main style={{width:540,padding:18,margin:'0 auto',background:'#17232f',color:'#e7eff8'}}><h2>多模型特效绑定</h2><EffectConfigurationInspector component={component} disabled={disabled} onChange={next=>{state.commits++;setComponent(next);}}/></main>;}
createRoot(document.getElementById('root')).render(<App/>);
`;
await writeFile(path.join(output, 'harness.tsx'), harness, 'utf8');
const storeFixture = { name: 'generated-follow-store-fixture', enforce: 'pre',
  resolveId(source, importer) {
    if (source === '/src/editor/store/editorStore' || source === '../store/editorStore' && /Effect(Configuration|DataBinding)Inspector\.tsx$/.test(importer ?? '')) return '\0generated-follow-store';
  },
  load(id) { if (id === '\0generated-follow-store') return "import {create} from 'zustand';export const useEditorStore=create(()=>({scene:null}));"; },
};
const bundle = path.join(output, 'bundle');
await build({ configFile: false, root: project, plugins: [storeFixture, react()], define: { 'process.env.NODE_ENV': '"production"' }, build: { lib: { entry: path.join(output, 'harness.tsx'), formats: ['es'], fileName: 'fixture', cssFileName: 'fixture' }, outDir: bundle, emptyOutDir: false, minify: false } });
const server = createServer(async (request, response) => {
  const file = request.url === '/fixture.js' ? 'fixture.js' : request.url === '/fixture.css' ? 'fixture.css' : null;
  response.setHeader('Content-Type', file?.endsWith('.js') ? 'application/javascript' : file ? 'text/css' : 'text/html');
  response.end(file ? await readFile(path.join(bundle, file)) : '<!doctype html><meta charset="utf-8"><link rel="stylesheet" href="/fixture.css"><div id="root"></div><script type="module" src="/fixture.js"></script>');
});
const errors=[];let browser;
try {
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  browser=await chromium.launch({channel:'msedge',headless:true});
  const page=await browser.newPage({viewport:{width:1280,height:1100}});page.setDefaultTimeout(15000);page.on('pageerror',error=>errors.push(error.message));
  await page.goto(`http://127.0.0.1:${server.address().port}/`);
  await page.getByRole('group',{name:'多个场景对象绑定',exact:true}).waitFor();
  assert.equal(await page.getByLabel('绑定模型 设备一',{exact:true}).isChecked(),true);
  assert.equal(await page.evaluate(()=>window.multiUi.component.configuration.target.entityIds),undefined);
  await page.getByLabel('绑定模型 设备二',{exact:true}).check();
  assert.deepEqual(await page.evaluate(()=>window.multiUi.component.configuration.target.entityIds),['m1','m2']);
  await page.getByRole('button',{name:'加入层级已选模型',exact:true}).click();
  assert.deepEqual(await page.evaluate(()=>window.multiUi.component.configuration.target.entityIds),['m1','m2']);
  await page.getByLabel('目标数量上限',{exact:true}).fill('2');
  assert.equal(await page.getByLabel('绑定模型 设备三',{exact:true}).isDisabled(),true);
  await page.getByLabel('目标数量上限',{exact:true}).fill('1');
  await page.getByRole('alert').filter({hasText:'请先移除对象'}).waitFor();
  assert.equal(await page.evaluate(()=>window.multiUi.component.configuration.target.maxTargets),2);
  await page.evaluate(()=>window.multiUi.removeModel('m2'));
  await page.getByRole('list',{name:'已绑定对象'}).getByText('对象不存在（m2）',{exact:true}).waitFor();
  assert.deepEqual(await page.evaluate(()=>window.multiUi.component.configuration.target.entityIds),['m1','m2']);
  await page.getByRole('button',{name:'移除绑定 m2',exact:true}).click();
  await page.getByLabel('绑定模型 设备三',{exact:true}).check();
  await page.getByLabel('特效数据来源',{exact:true}).selectOption('inherit');
  await page.getByRole('button',{name:'测试取数',exact:true}).click();
  await page.getByRole('alert').filter({hasText:'选择一个试取数目标'}).waitFor();
  await page.getByLabel('多模型试取数目标',{exact:true}).selectOption('m3');
  await page.evaluate(()=>window.multiUi.publish('0003'));
  const boundBeforeProbe=await page.evaluate(()=>JSON.stringify(window.multiUi.component.configuration.target));
  await page.getByRole('button',{name:'测试取数',exact:true}).click();
  await page.getByRole('status').filter({hasText:'状态：在线'}).waitFor();
  assert.equal(await page.evaluate(()=>JSON.stringify(window.multiUi.component.configuration.target)),boundBeforeProbe);
  await page.evaluate(()=>window.multiUi.diagnostic({status:'waiting',message:'部分目标等待数据',candidates:[],identity:null,fields:{},updatedAt:null,targetStates:[{id:'m1',name:'设备一',status:'online',message:'数据已更新',identity:{sourceId:'factory-a',deviceType:'rgv',assetCode:'0001'}},{id:'m3',name:'设备三',status:'invalid',message:'共享薄实例不支持单独模型表面效果',identity:null}]}));
  await page.getByText('运行诊断',{exact:true}).click();
  await page.getByText('逐目标状态（2）',{exact:true}).click();
  await page.getByText('invalid：共享薄实例不支持单独模型表面效果',{exact:true}).waitFor();
  await page.getByText('factory-a / rgv / 0001',{exact:true}).waitFor();
  await page.getByRole('group',{name:'多个场景对象绑定',exact:true}).scrollIntoViewIfNeeded();
  await page.screenshot({path:path.join(output,'explicit-model-binding.png'),fullPage:false});
  const beforeLock=await page.evaluate(()=>({value:JSON.stringify(window.multiUi.component),commits:window.multiUi.state.commits}));
  await page.evaluate(()=>window.multiUi.setDisabled(true));
  await page.waitForFunction(()=>document.querySelector('[aria-label="绑定模型 设备一"]')?.disabled);
  assert.equal(await page.getByRole('button',{name:'清空已绑定对象',exact:true}).isDisabled(),true);
  assert.equal(await page.getByLabel('绑定模型 设备三',{exact:true}).isDisabled(),true);
  assert.deepEqual(await page.evaluate(()=>({value:JSON.stringify(window.multiUi.component),commits:window.multiUi.state.commits})),beforeLock);
  await page.evaluate(()=>window.multiUi.setDisabled(false));
  await page.getByRole('button',{name:'清空已绑定对象',exact:true}).click();
  assert.deepEqual(await page.evaluate(()=>window.multiUi.component.configuration.target.entityIds),[]);
  assert.equal(await page.evaluate(()=>window.multiUi.component.configuration.target.entityId),null);
  await page.getByLabel('特效目标来源',{exact:true}).selectOption('model');
  const transfer=await page.evaluateHandle(()=>{const data=new DataTransfer();data.setData('application/x-babylon-editor-model-asset',JSON.stringify({id:'device-template',name:'设备类型.glb',path:'C:/fixture/device.glb',sourceUrl:'editor-asset://local/device.glb',kind:'model',libraryKind:'model'}));return data;});
  await page.getByRole('region',{name:'特效模型模板拖放区'}).dispatchEvent('drop',{dataTransfer:transfer});
  assert.equal(await page.getByLabel('目标匹配方式',{exact:true}).inputValue(),'all');
  assert.equal(await page.evaluate(()=>window.multiUi.component.configuration.target.entityIds),undefined);
  await page.getByLabel('特效实例来源',{exact:true}).selectOption('generated');
  await page.getByLabel('特效生成器范围',{exact:true}).selectOption('generator');
  await page.getByLabel('特效实例编号类型',{exact:true}).selectOption('containerCode');
  await page.getByRole('status').filter({hasText:'等待运行时生成'}).waitFor();
  assert.equal(await page.evaluate(()=>window.multiUi.component.configuration.target.instanceKey),'containerCode');
  await page.evaluate(()=>window.multiUi.setComponent({...window.multiUi.component,effectKind:'motion-trail'}));
  assert.equal(await page.getByLabel('目标匹配方式',{exact:true}).isEnabled(),true);
  assert.equal(await page.getByLabel('目标匹配方式',{exact:true}).inputValue(),'all');
  await page.screenshot({path:path.join(output,'multi-model-binding.png'),fullPage:false});
  await page.evaluate(()=>window.multiUi.setComponent({...window.multiUi.component,effectKind:'target-follow'}));
  assert.equal(await page.getByLabel('目标匹配方式',{exact:true}).count(),0);
  await page.getByLabel('特效目标来源',{exact:true}).selectOption('entity');
  await page.getByLabel('详细配置场景对象',{exact:true}).selectOption('m3');
  assert.equal(await page.evaluate(()=>window.multiUi.component.configuration.target.entityId),'m3');
  assert.equal(await page.evaluate(()=>window.multiUi.component.configuration.target.entityIds),undefined);
  assert.equal(await page.evaluate(()=>window.multiUi.component.configuration.target.selection),'single');
  await page.evaluate(()=>window.multiUi.setComponent({...window.multiUi.component,effectKind:'environment-fog'}));
  assert.equal(await page.getByLabel('特效目标来源',{exact:true}).count(),0);
  assert.deepEqual(errors,[]);
  const result={passed:true,errors,scenarios:['legacy entityId preserved until edit','explicit multi selection','hierarchy selection deduplicated','target cap and decrease validation','missing reference retained and removable','per-target inherit probe without binding mutation','locked controls cannot mutate','explicit empty selection','model drop defaults all','generated source and identity filters','multi target motion trail enabled','camera follows one target','global environment target UI hidden','per target runtime diagnostics']};
  await writeFile(path.join(output,'result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
} finally {await browser?.close();server.closeAllConnections();await new Promise(resolve=>server.close(resolve));}
